### ISSUE TITLE
Add functionGlobalContext to settings.js

### ISSUE THREAD

**Issue by corndog2000** [marcus-j-davies/Node-RED-SFE#2]
Hello,

I would like to add custom require lines to functionGlobalContext in the portable app.

How can I add these changes to the compiled program?

`
functionGlobalContext: {
// os:require('os'),
serialportModule:require('serialPort')
}
`

**Comment by marcus-j-davies** [comment]
Hi

In the root package file (https://github.com/marcus-j-davies/Node-RED-SFE/blob/main/package.json), ensure `serialport` is listed in the dependencies, perform the install to pull down the dependencies.  

Then you will need to modify `node-red.js`
https://github.com/marcus-j-davies/Node-RED-SFE/blob/f4358c4c550ca75d595be8c62ef6c57bc78d1a2c/node-red.js#L104

To add the export as normal.

Note: I have not tested doing that - but it should work, embedding a Node that uses `serialport` works, so can't see why it wouldn't 

I should add the ability to allow this in settings.js - but it gets overwritten, so I'll get that improved soon

**Comment by marcus-j-davies** [comment]
There you go - you can now freely use (or not) `functionGlobalContext`

https://github.com/marcus-j-davies/Node-RED-SFE/commit/13c64c1d58f0362fa8c9ac36a42722cb670ea1cd
