### ISSUE TITLE
Error when running `npm run-script package`

### ISSUE THREAD

**Issue by HaroldPetersInskipp** [marcus-j-davies/Node-RED-SFE#4]
npm run-script package

> package
> cd ./build && pkg ./package.json --compress gzip -t host --targets node20 --output ./dist/node-red-sfe

> pkg@5.12.0
compression:  GZip
> Warning Cannot resolve 'moduleDir'
  C:\Users\Bannd\Downloads\GameDev\Node-RED-SFE-main\build\node-red-bundle.js
  Dynamic require may fail at run time, because the requested file
  is unknown at compilation time and not included into executable.
  Use a string literal as an argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
> Warning Cannot resolve 'relPath'
  C:\Users\Bannd\Downloads\GameDev\Node-RED-SFE-main\build\node-red-bundle.js
  Dynamic require may fail at run time, because the requested file
  is unknown at compilation time and not included into executable.
  Use a string literal as an argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
> Warning Cannot resolve 'parsedModule.module + parsedModule.subpath'
  C:\Users\Bannd\Downloads\GameDev\Node-RED-SFE-main\build\node-red-bundle.js
  Dynamic require may fail at run time, because the requested file
  is unknown at compilation time and not included into executable.
  Use a string literal as an argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
> Warning Cannot resolve 'mod'
  C:\Users\Bannd\Downloads\GameDev\Node-RED-SFE-main\build\node-red-bundle.js
  Dynamic require may fail at run time, because the requested file
  is unknown at compilation time and not included into executable.
  Use a string literal as an argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
> Warning Cannot resolve 'moduleInfo.path'
  C:\Users\Bannd\Downloads\GameDev\Node-RED-SFE-main\build\node-red-bundle.js
  Dynamic require may fail at run time, because the requested file
  is unknown at compilation time and not included into executable.
  Use a string literal as an argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
> Warning Cannot resolve 'path.join(__dirname, "..", "package.json")'
  C:\Users\Bannd\Downloads\GameDev\Node-RED-SFE-main\build\node-red-bundle.js
  Dynamic require may fail at run time, because the requested file
  is unknown at compilation time and not included into executable.
  Use a string literal as an argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
> Warning Cannot stat, ENOENT
  C:\Users\Bannd\Downloads\GameDev\Node-RED-SFE-main\build\node-red-ask-pass.sh
  The file was required from 'C:\Users\Bannd\Downloads\GameDev\Node-RED-SFE-main\build\node-red-bundle.js'
> Warning Cannot stat, ENOENT
  C:\Users\Bannd\Downloads\GameDev\Node-RED-SFE-main\build\authWriter.js
  The file was required from 'C:\Users\Bannd\Downloads\GameDev\Node-RED-SFE-main\build\node-red-bundle.js'
> Warning Cannot stat, ENOENT
  C:\Users\Bannd\Downloads\GameDev\Node-RED-SFE-main\build\node-red-ask-pass.sh
  The file was required from 'C:\Users\Bannd\Downloads\GameDev\Node-RED-SFE-main\build\node-red-bundle.js'
> Warning Cannot stat, ENOENT
  C:\Users\Bannd\Downloads\GameDev\Node-RED-SFE-main\build\authWriter.js
  The file was required from 'C:\Users\Bannd\Downloads\GameDev\Node-RED-SFE-main\build\node-red-bundle.js'
> Warning Cannot stat, ENOENT
  C:\Users\Bannd\Downloads\GameDev\Node-RED-SFE-main\build\node-red-ssh.sh
  The file was required from 'C:\Users\Bannd\Downloads\GameDev\Node-RED-SFE-main\build\node-red-bundle.js'

**Comment by marcus-j-davies** [comment]
Hey @HaroldPetersInskipp 
These are warnings to be expected. 

I think it’s just pkg being a little worried, they have never caused a problem (yet)
