### ISSUE TITLE
How to complie  in Node-Red v3 / node v18

### ISSUE THREAD

**Issue by apm29** [marcus-j-davies/Node-RED-SFE#5]

**Comment by marcus-j-davies** [comment]
Hi @apm29 

To target Node RED 3, Node18, a few things need to be patched, modified.

 - Set the `node-red` version in the `package.json` file
 ```
 "dependencies": {
		"@yao-pkg/pkg": "^5.12.0",
		"esbuild": "^0.23.0",
		"node-red": "^3.1.11",
		"winston": "^3.13.1",
		"winston-daily-rotate-file": "^5.0.0"
	},
 ```
 
  - Add 3 more modules that needs to be skipped during ESBuild
  ```
  /* Things to not include during bundling */
const externals = [
	...Others

	'mock-aws-s3', 
	'aws-sdk',
	'nock',

];
  ```
  
 - Patch the ESBuild commands to target node18
    
```
    const config = {
		entryPoints: [file],
		bundle: true,
		platform: 'node',
		target: 'node18',
		allowOverwrite: true,
		outfile: file
	};
```

And to compile using Node 18, you need to change the `package` command

```
"package": "cd ./build && pkg ./package.json --compress gzip --targets node18-win-x64 --output ./dist/node-red-sfe"
```

```
node[Version]-[platform]-[architecture]
platform is : win, linux, macos
using  --targets host, will use the current environment, to decide what to build and what version of node 
```

**Comment by marcus-j-davies** [comment]
Ooh! and add .html files in the `nativeNodeModulesPlugin` plugin.

```
const opts = build.initialOptions;
opts.loader = opts.loader || {};
opts.loader['.node'] = 'file';
opts.loader['.html'] = 'file';
opts.loader['.sh'] = 'binary';
```

**Comment by apm29** [comment]
thanks very much! I'll try it later

**Comment by marcus-j-davies** [comment]
The steps above result in a working build of Node RED 3 with Node 18

I am a Mac user, so for me it was : `--targets node18-macos-arm64` (get rid of `-t host`) -its an error, and I need to remove it

![Screenshot 2024-08-17 at 08 07 08](https://github.com/user-attachments/assets/bf255d49-e225-4264-86df-c997f47cb5cb)

![Screenshot 2024-08-17 at 08 09 07](https://github.com/user-attachments/assets/f87be0c2-3dae-4d75-bb5f-ca564fb47f7f)

**Comment by apm29** [comment]
I've packaged it successfully and It works well now , thanks, It helps me much !
